### ISSUE TITLE
Section 6 - Solution Sketch - Feb 5th

### ISSUE THREAD

**Issue by argo49** [argo49/soen-scheduler#14]
This section gives an early overview of the solution you propose for the project.
This section should include the rationale of your decisions. A rationale exhibits a valid justification for a given decision made in the course of planning your solution. It should explain the reasons why a decision was made. It should justify whether or not this decision is “wise” by comparing it with some others.

6.1    Architecture
Explain the high-level system architecture that you plan for the project, giving explanations as to why you chose such an approach, e.g. a design rationale. Include a high-level architecture diagram (e,g, a high-level UML class diagram). For each module presented in the architecture, also give its rationale, as well as list their individual responsibilities.

6.2    Technologies in Use
List all the technologies that you plan to use in the project (e.g. programming languages, tools like compiler or IDE, libraries, etc. Give a brief rationale for the use of each technology, i.e. explanations describing why they are appropriate in the context of this project.

**Comment by glachov** [comment]
Today I spoke with the Prof about section 6.1. and the high-level UML class diagram. He clarified that it should be a class diagram with the main classes and on the next stage we have to develop a more detailed class diagram. However in the projects from the previous years they have just Model-View-Controller model as this section is called Architecture (one of them looks alike UML). Kristina and I, we were thinking to included both. What do you think about that?
