### ISSUE TITLE
Section 7 - Plan - Feb 10th

### ISSUE THREAD

**Issue by argo49** [argo49/soen-scheduler#15]
Assignees: Samer, Buruc, Gaston

This section contains the schedule for the project, as directed by all the information presented in the preceding sections.

7.1 Activities
Describe what are the main activities involved in your project. An activity is something that must be undertaken in order to produce an artifact that is useful in reaching the goals of the project. Each activity shall have a clear purpose, and shall yield at least one artifact as an output.

7.2    Artifacts
Describe what are the artifacts you are going to produce in this project. Do not limit yourself to “deliverable 1, deliverable 2 and deliverable 3”, but rather split them into lower level units, e.g. “class diagram”, “list of requirements”, “test cases”, etc. Explanations describing the role of each artifact in the production process. 

7.3    Project Estimates
Provide a realistic estimated cost and schedule for the project, as well as the basis for those estimates, and the points and circumstances in the project when re-estimation might occur.
Evaluate the cost of production of each artifact, as described in the previous section, and then adding up the numbers.

7.4    Activities Assignments
Assign the different activities to your team members, according to their capacities and schedule limitations, as presented in section 4.1.

7.5    Schedule
Diagrams or tables showing target dates for completion of iterations and phases, release points, demos, and other milestones, e.g. a Gantt chart.

7.6    Risk
List and comment all the elements of the project that present a risk. Explain why they represent a risk.

**Comment by ghost** [comment]
***********_Mine is wrong, so working on @basrin's one is the right one!**_*****************************
![plan12](https://f.cloud.github.com/assets/6386263/2089684/73bb532a-8e8a-11e3-9cc5-9c1007b53f5d.png)

**Comment by MWarsame** [comment]
Here is what I have planned for testing so you don’t have to guess.

Activity: Testing and Debugging Phase
Purpose: To ensure all functional requirements are met.
    Participants: ___________________________
Estimated Duration: 70 hours ← seems a bit excessive
    Duration: _________________________

Artifact:  Apply fundamental test suites
Description: Test the structural integrity of application. 
Estimated Time: 12 hours

Artifact: Cross browsing and multiple hardware platform consideration
    Description: Verify whether all browsers and devices are supported.
Estimated Time: 6 hours

Artifact: Prepare test cases for unit, integration and stress tests for client-side
    Description: Assemble all test cases to facilitate transcription into frameworks.
Estimated Time: 8 hours

Artifact: Prepare test cases for server-side
Description: Assemble all test cases to facilitate transcription into framework.
Estimated Time: 8 hours

Artifact: Unit Test
Description: Ensure all functions are implemented accordingly.
Estimated Time: 10 hours

Artifact: Segmentation Test 
Description: Test functions and modules to ensure they work in unison.
Estimated Time: 5 hours

Artifact: Stress tests
Description: Verify security and robustness of application.
Estimated Time: 21 hours

**Comment by basrin** [comment]
I put up in section 7 the Activities and Artifacts skeleton table (on google drive). It has 5 columns: 
1) Roman numeral numbering for the Activities
2) Activities: what I refer to as big buckets that contain the artifacts 
3)Artifacts: these are by-products of Activities, any task you can think of find a bucket and make a row for it
4)Description: an explanation describing the artifact
5)Participants: members assigned to do this artifact (self-assign yourselves where suitable)
6)Estimated man hours: estimated time to complete this artifact. For those who don't know, man hours work the following way: i.e. 6 man hours can mean 6people \* 1hour or 1person*6hours.

Directives:
Please fill up any section which may concern you. Do not hesitate to modify or do major surgery to the table it needs to be detailed for us to go "above and beyond". Add rows, delete rows if you feel the buckets are wrong give us a heads up before moving a new one in.

Please reference the "Example of activities and artifacts" PDF I put up on the google drive which shows the inspiration for our table, a cross between Nexus and the Stars.

Formatting Concerns:
Google doc is not ideal, I would like to have similarly to Nexus, rows within the same activity to be border-less and also merge any of the empty cells. Google doc doesn't seem to have these capabilities.
Colors I'll leave to the formatting team (Tyler?) maybe implement similar to Nexus alternating the row colors to increase readability.
Lastly, I think the table needs to be in Landscape considering its size.

**Comment by ghost** [comment]
Thanks MWarsame, that cleared things up for me.
K barsin, i am gonna check it out and work on it today. Also, for section Schedule i am gonna do it. It should be easy once we have completed the Activities, Artifacts. I just have to fill it out... But please guys feel free to modify once i finish it.

**Comment by glachov** [comment]
About 7.6. Risk

Risk magnitude = Rate (or probability) of occurrence x  the impact of the event (http://en.wikipedia.org/wiki/Risk_management)

For example we can rank the probabilities of delay of a task from 1 to 5 (2 means 20% probability delay)
Let's say we estimate that a task is 10 h. and it is rank is 2 ( so the risk is 20%)
We have 10 h x 0.20 = 2 h possible delay and we have to increase our estimation for this task with 2 hours to be 100% sure. If we have the time of all tasks and rank their probabilities of delay we can estimate the Composite Risk Index = Impact of Risk event x Probability of Occurrence, This can be used as reasoning to increase our estimated time.

I found an article about software risk assessment and you can find types of risk in  Figure 2. Expert COCOMO Risk Taxonomy [http://www.academia.edu/3152392/Software_Project_Risk_Assessment_based_on_Cost_Factors_and_Fuzzy_Technique]
You can just list them. In previous projects I saw that Stars has something similar but we can do it better.

**Comment by glachov** [comment]
About risk ranking and risk management
http://www.jiscinfonet.ac.uk/infokits/risk-management/qual-analysis/
http://www.jiscinfonet.ac.uk/wp-content/uploads/risk-values-equal-scale.png
"Red risks = Unacceptable. We must spend time, money and effort on a response. This is likely to be at the level of the individual risk.Green risks = Acceptable. This does not mean they can be ignored. We will cover them by means of contingency. This means setting aside a sum of money to cover this group of risks. We will look at how you calculate this sum in the section on Calculating Contingency."

**Comment by basrin** [comment]
@argo49 @MWarsame @glachov @niofire @BloZ-C @coolhatharry @red-areios @AmmarB341 @klachov @GastonMatos @samerela 
Section 7 needs to be filled up by everyone for us to be able to finish the rest of the section. Please look at my post above so it's clear on how to go about putting your info in the table. If you got any questions please let me know!

**Comment by GastonMatos** [comment]
I am doing the risk part instead of @samerela . DONE !!!! if @glachov wants to add more stuff from what i heard, he can go to the Google drive, it is posted.

**Comment by glachov** [comment]
I saw  the estimated tasks in hours in the Deliverable 1 but I need the Gantt diagram also for the development of the critical path of our project. Please add it when it is ready.

Also about the risk we can use the next Fig.
![risk-values-equal-scale](https://f.cloud.github.com/assets/6385357/2133251/27e9d054-92c0-11e3-97c5-ffe0323326ca.png)
http://www.jiscinfonet.ac.uk/infokits/risk-management/qual-analysis/
Green mean that this task is fine; yellow - we have to plan something to do if this happens, red - we must have plan of actions. It won't be difficult to calculate it: we have the impact and the probability in the use cases. Each task belongs to an use case so it takes its impact and probability. 

What do you think about this?

**Comment by argo49** [comment]
I like it! It's a very visual way of showing risk and I think they'll really like it. Also it would look good in the documentation

**Comment by ghost** [comment]
This is a link for scheduler http://www.smartsheet.com/.

**Comment by c-robi** [comment]
Please add the scheduler to the document if you're done. We do not have a lot of time left!

**Comment by glachov** [comment]
I logged in. Please add me.

**Comment by ghost** [comment]
K guys i added everyone to the scheduler so you can check your email. You can modify/add.. the scheduler, fell free. I am working now on the predecessors of the artifacts. But be careful because when you put a predecessor for an artifact, this artifact (successor) start day will begin after the end of its predecessor.

**Comment by ghost** [comment]
Days for each deliverable:
D0 -> Max day is 8
D1 -> Max day is 19
D2 -> Max day is 23 
D3 -> Max day is 16
D4 -> Max day is 8

**Comment by ghost** [comment]
Once it is finished the, i think we should only put the scheduler figure not with the task names. Task names shows that we have a lot of artifacts but in reality it is divided in sub-activities.

**Comment by glachov** [comment]
just to let you know I am working on 7.4. Risk in the doc file

**Comment by ghost** [comment]
The Scheduler is finished !

**Comment by c-robi** [comment]
Is it being added to the Word document? Please use the FIXED .docx file under the Formatted folder.

**Comment by glachov** [comment]
7,4, Risk is added in the folder Formatted in a doc file called  7.4 Risk.docx

**Comment by glachov** [comment]
I saw that the Scheduler is added not to the doc file but to the Deliverable 1 (on Google Drive ) in the end
