### ISSUE TITLE
Create A Logo!

### ISSUE THREAD

**Issue by argo49** [argo49/soen-scheduler#19]
All team logo discussion should be done here. We'll close this issue when we decide on a logo! I was thinking something simple like this, but @glachov has a good point that our logo should have some kind of meaning, You can read his comment [here](https://github.com/argo49/soen-scheduler/issues/17).

![](https://dl.dropboxusercontent.com/u/9808252/soen341/logo1.png)

**Comment by ghost** [comment]
I like this logo because it matches the website style, and represent solidity which can also means reliability. I came with one but it feels like it for driving car logo but anyways here it is: 
![logo](https://f.cloud.github.com/assets/6386263/2061570/a539169e-8c5a-11e3-9915-665d1e690fcd.png)

**Comment by niofire** [comment]
Modified a bit the original logo posted by Tyler, I can do anything within these areas of design
![logo](https://f.cloud.github.com/assets/2295469/2066851/03eb3386-8cf4-11e3-90dc-9041c2ec9c1c.png)

White line is weird, I could take it out as well

**Comment by coolhatharry** [comment]
Okay so we're spending too much time on the logo, we should stick to the
A+, because the logos of argonauts does not make sense for a schedule
generator.

**Comment by glachov** [comment]
Just an idea: what about if we use both logos?  The argo49&noifire's logo is the logo of the team (btw it's really nice - great job guys!) and it can appear on the project documents etc. as well the A+ and the slogan can be on the scheduler. Lets say the team as a company has it's own logo and we can develop different product with their own logos. For example the company that produces Barby dolls has another brand for boys toys (Fisher&Price). What do you think about that? But please guys as  @coolhatharry already said don't spend too much time on it.

**Comment by argo49** [comment]
Alright so I took @glachov 's A+ design and made it fit a tiny bit more with the angled design of the app. Would everybody be okay with using this as our logo?
![](https://dl.dropboxusercontent.com/u/9808252/soen341/logo2.png)

**Comment by coolhatharry** [comment]
The logo is perfect, the rest are great too, but this gives it a double meaning.

**Comment by glachov** [comment]
I like it :)

**Comment by ghost** [comment]
I agree with A+ logo.

**Comment by AmmarBaali** [comment]
I made this one quickly using a program I found online. The A+ proposed above is nice too so whichever one you guys want.. (The third image with just the A is for the headers)

![possible_logo](https://f.cloud.github.com/assets/6384839/2119293/6aba654a-915a-11e3-984c-ba677a1566ca.png)
![possible_logo_scheduler](https://f.cloud.github.com/assets/6384839/2119371/129890e8-9160-11e3-82e6-5dbaabc3fba2.png)
![logo4headers](https://f.cloud.github.com/assets/6384839/2119292/6ab7748e-915a-11e3-9fa3-9aa1cec6180e.png)

**Comment by basrin** [comment]
We spoke about having a section explaining the philosophical meaning or justification of our logo, something about the ship story. Let's not forget to include this in our project.

**Comment by glachov** [comment]
I was thinking to add it in a foreword at the beginning of the final project

**Comment by coolhatharry** [comment]
Yes that's a good idea, will also give us some bonus points, good job.
