### ISSUE TITLE
What Subsystems and Components?

### ISSUE THREAD

**Issue by c-robi** [argo49/soen-scheduler#24]
Hey folks,

I'm opening this issue to figure out what subsystems and components to use. Nobody seems to have described the subsystems yet so we should be able to change them a bit.

We currently have this list of subsystems (from the whiteboard):
- Exporter
- Registration Management
- Schedule Generation
- Schedule Manipulation
- 3PP (third-party programs)
  We have not defined any components yet.

The problem is that I think we might have mixed up subsystems and components (also known as modules). At least Exporter and 3PP look like components to me. Does anybody think that we could refine the list?

Personally, I don't get the difference between a subsystem and a component: the professor basically told me they were the same thing, then said they weren't, and that subsystems are at a higher level than components (something like that). He confused me more than anything. If anyone knows the real difference, let us know.

**Comment by ghost** [comment]
I am currently working on the Subsystem Interfaces Specifications, and i am also working on refining the subsystem names.. I will keep updating my work in google drive, if you guys want to edit..
I think components is the same as subsystems.

**Comment by niofire** [comment]
subsystem is a group of components. Also, a subsystem is a component itself.http://www.uml-diagrams.org/component-diagrams.html

Date: Sun, 9 Mar 2014 14:37:00 -0700

**Comment by c-robi** [comment]
Thanks for the explanation! I'm guessing that's what the professor meant. We can probably keep our current subsystems, and whoever works on the component diagram (currently Buruç) can divide the subsystems into some more components.

**Comment by basrin** [comment]
Thanks for the clarifications I'll continue working on it.
