### ISSUE TITLE
Scoping ideas whiteboard pictures

### ISSUE THREAD

**Issue by niofire** [argo49/soen-scheduler#6]
Anybody knows where the pictures of the features list has been put?

**Comment by argo49** [comment]
I posted it in the wiki some days ago but I forgot to update the main wiki page. Sorry about that. If you click on the "pages" tab at the top of the wiki you'll see all the entries and the features list is there. [Here's a hyperlink](https://github.com/argo49/soen-scheduler/wiki/Features-List) to save you the trouble though. I'll go add it to the main wiki hub.

**Comment by niofire** [comment]
Good stuff, thanks!
