### ISSUE TITLE
GUI interface drawing plan

### ISSUE THREAD

**Issue by niofire** [argo49/soen-scheduler#8]
Draw a plan of the GUI (Actual drawing)

**Comment by argo49** [comment]
To help with this I made a colour palette! In general I think it would be a good idea to stick with these colours. They're kind of based on Concordia's official colour scheme to make it feel more like an official tool.
https://dl.dropboxusercontent.com/u/9808252/palette.png?dl=1
![](https://dl.dropboxusercontent.com/u/9808252/palette.png)

**Comment by niofire** [comment]
I'll bring my color crayons tuesday :)

**Comment by argo49** [comment]
A User experience flowchart of sorts. I think this could probably find a home in Deliverable 2. Don't hesitate if you have any questions about it!

![](https://dl.dropboxusercontent.com/u/9808252/soen341/341%20-%20UX%20FLowchart%20-%20New%20Page.png)

**Comment by coolhatharry** [comment]
Looks good, well done. I would just put the arrow going from Login Page(1) to User Homepage(6) below everything. Make the arrow from (2) -> (6), so the arrow is going from the right side of (2) to the left side of (6).

**Comment by argo49** [comment]
Oh right forgot that arrow :P not sure what you mean about the 2 -> 6 thing though :S
![](https://dl.dropboxusercontent.com/u/9808252/soen341/341%20-%20UX%20FLowchart%20-%20New%20Page%20%282%29.png)

**Comment by coolhatharry** [comment]
Could you send me a link, I'll fix it up.

**Comment by argo49** [comment]
Here you go!

http://www.lucidchart.com/invitations/accept/53062183-1a18-4336-bf5e-61fd0a009b21

**Comment by coolhatharry** [comment]
Here it is:
![341 - ux flowchart - new page](https://f.cloud.github.com/assets/6371666/2222852/414c51b4-9a6a-11e3-96b4-8afc2d3886dd.png)

**Comment by niofire** [comment]
For the mockup, do you know if the profile page is going to be done before our deliverable 2 deadline?

**Comment by argo49** [comment]
It definitely should be. I'll keep you posted.

**Comment by klachov** [comment]
I'm making the Authorization Activity Diagram and I'm following the above flowchart. I want to ask you if I understand correctly: when someone is first time logging in with a facebook account a new profile is created automatically without to be send an activation code, right?
